### ISSUE TITLE
Allow mods to edit other people's trades

### ISSUE THREAD

**Issue by TheSonAlsoRises** [YaManicKill/flairhq#136]
It could always be useful.

**Comment by YaManicKill** [comment]
Do we still want this to be a thing? What's the use-case for it?

**Comment by TheSonAlsoRises** [comment]
The original idea was (probably) to edit blatant mistakes. Now that we have an auto approval of the trades, it is most likely no longer required.

**Comment by YaManicKill** [comment]
Cool. I think that we are unlikely to ever actually use it, but rather send it back to them for editing.
