### ISSUE TITLE
Special characters issues

### ISSUE THREAD

**Issue by TheSonAlsoRises** [YaManicKill/flairhq#155]
One of our members has the following flair:

`&lt;3`

It is a result of a bug from the bot and should display `<3`.

FAPP displays it on their profile as:

`&amp;lt;3`

**Comment by YaManicKill** [comment]
Is this still the case?

**Comment by TheSonAlsoRises** [comment]
I have not encountered that issue recently.

**Comment by YaManicKill** [comment]
Meh, I'll close it until we see it again. I think I may have accidentally fixed it sometime.
