### ISSUE TITLE
Popovers with explanations?

### ISSUE THREAD

**Issue by NotRaia** [YaManicKill/flairhq#163]
Due to the number of users inputting wrong things in the fields, it may be worth having something telling them what exactly goes in the box. At least for the username field, specifying that it's the person they traded with/hatched for and that it could work with or without the /u/.

**Comment by YaManicKill** [comment]
This might still be worth doing, as people don't read the how-to, and this would help explain the different categories.

**Comment by YaManicKill** [comment]
I'm going to finally get this done this week, I think. It really should take long, and will help so much.

**Comment by YaManicKill** [comment]
Done. Deploying soon.
