### ISSUE TITLE
http and https permalinks are incorrectly treated as different

### ISSUE THREAD

**Issue by NotRaia** [YaManicKill/flairhq#179]
Check out 26 and 27 of my shiny trades, they are totally duplicates of 19 and 20. Only difference is https.

**Comment by NotRaia** [comment]
This is actually kind of important now, because reddit is forcing everyone to use https.

**Comment by YaManicKill** [comment]
Surely that means it's less of an issue because they won't input http
links.

**Comment by TheSonAlsoRises** [comment]
Nothing is stopping a user from re-using the http links and inputting them again, prefixing this time the links with http**s**. FHQ will not detect it.

**Comment by YaManicKill** [comment]
Well yes, I understand why it needs fixed, what I didn't understand is why
it's more of an issue now than before. Seeing as https has been default for
ages.

**Comment by TheSonAlsoRises** [comment]
https has been available for some time, but the site defaulting to https is a recent development (two weeks ago). See here: https://www.reddit.com/r/redditdev/comments/39zje0/reddit_will_soon_only_be_available_over_https/
