### ISSUE TITLE
Show the total of eggs/Pokémon given away

### ISSUE THREAD

**Issue by TheSonAlsoRises** [YaManicKill/flairhq#191]
Can FHQ display in a more prominent fashion the number of Pokémon/eggs checked/given away for each entry? Can we have a grand total listed somewhere?

**Comment by YaManicKill** [comment]
Why is this in blocked? We still want this done?

**Comment by TheSonAlsoRises** [comment]
I would still be up for it.

**Comment by YaManicKill** [comment]
Alrighty, how would we want it done? Where would a grand total go?

**Comment by TheSonAlsoRises** [comment]
Probably as a tally below each table, or at the bottom of the page?

**Comment by YaManicKill** [comment]
Hmmm possibly. I'll have a play, see what I think about where it could go.
