### ISSUE TITLE
Possible counting issue

### ISSUE THREAD

**Issue by TheSonAlsoRises** [YaManicKill/flairhq#197]
http://hq.porygon.co/u/bloozchicken

http://i.imgur.com/J8QMqaT.png

http://i.imgur.com/lP3gews.png

They applied for a Lucky Egg but do not have the required 5 hatches. Maybe they deleted one, maybe it is a bug.

**Comment by NotRaia** [comment]
Maybe we should just not let users delete trades if they have a pending flair app?

**Comment by YaManicKill** [comment]
That doesn't feel ideal. Could we check when they delete something if that takes them below the line and then remove their application? It could be not great, but is another idea.

**Comment by TheSonAlsoRises** [comment]
Honestly the issue does not come up often, any potential fix may not be worth the time.

**Comment by YaManicKill** [comment]
That's what I like to hear.
