### ISSUE TITLE
Indicate to users that their flair app is in the queue

### ISSUE THREAD

**Issue by NotRaia** [YaManicKill/flairhq#198]
https://www.reddit.com/r/pokemontrades/comments/2qflm0/daily_discussion_thread_for_26_december_2014/cn60vjd

**Comment by YaManicKill** [comment]
Interesting idea. Not really high priority. Maybe after pokelist?

**Comment by NotRaia** [comment]
>stick a story in the backlog

You mean... like these stories?

* As a user, I want to know if my flair app is in the queue, because I don't trust my memory.
* As a mod, I want to see what flair someone applied for on their profile, so I don't have to check back in the flair app list.
* As a mod, I want to see how many trades/hatches/giveaways/tradebacks is required for a user's flair app, because I'm not used to the new flair levels.

**Comment by YaManicKill** [comment]
Right, I'll start work on this soon.

Question:

Where do we want to show it.

1 obvious option is when someone goes to the apply page, it can say "You have already applied for: flair. If you apply for another flair on /r/pokemontrades, this will overwrite it." or something.

Do we want anymore than that?

**Comment by TheSonAlsoRises** [comment]
You would have to account for the existence of different subreddits, and types of flairs for trades (involvement/ball) and SVeX (egg/ribbon). I would keep it simple with a single message "You already have a flair application in the queue" to be cleared when denied/granted.

**Comment by YaManicKill** [comment]
Well yeah, the message was to take into account different subs. It doesn't
solve the multiple flairs but I could just modify the message depending on
which they have.

If I just have a generic message, it means that if they have 1 app in they
don't know if a second one went through.

**Comment by YaManicKill** [comment]
Fixed, I decided to do this: http://imgur.com/DXJ8f1k
