### ISSUE TITLE
Leaving messages on user's flairs from a phone

### ISSUE THREAD

**Issue by isaelsky21** [YaManicKill/flairhq#211]
Hey,

I'm currently having issues leaving messages on users' flairs from my Samsung Galaxy S4.

I tried from the "reddit is fun" app and the chrome browser with no success.

Is it not supported on mobile platforms?

Thanks.

**Comment by YaManicKill** [comment]
It is meant to be supported. That's a bug. I'll look into that. Thanks.

**Comment by YaManicKill** [comment]
This still an issue? Not looked into it properly. Will look at it later this week.

**Comment by NotRaia** [comment]
Looks like it is: https://www.reddit.com/r/pokemontrades/comments/39b6v5/minor_flairhq_changes/cs1vtpw

**Comment by YaManicKill** [comment]
Totally just fixed this. Was a really easy fix (don't tell my boss I'm not doing work).
