### ISSUE TITLE
Rename "Involvement Trades" -> "Tradebacks"

### ISSUE THREAD

**Issue by NotRaia** [YaManicKill/flairhq#219]
Since they are technically not considered trades.

http://i.imgur.com/A5agLOn.png

**Comment by NotRaia** [comment]
(wait for TSAR on this one)

**Comment by TheSonAlsoRises** [comment]
I wanted to rename the entire section "Involvement Flair", but I am open to suggestions.

**Comment by YaManicKill** [comment]
I'm fine with Involvement Flair, I had just put the section as "Involvement
Trades" and Raia pointed out that they are not trades. I'll change it to
Flair.

-------------------------------------

Alistair McKinlay
alistair@10people.co.uk
http://www.10people.co.uk
