### ISSUE TITLE
Involvement flair requirements is incorrectly going based off of number given (from the wrong sub too)

### ISSUE THREAD

**Issue by NotRaia** [YaManicKill/flairhq#222]
My SVeX "giveaway" with 100 given counted towards the poketrades involvement flair total and it let me apply for flair. However, my poketrades giveaway with 2 does not increment the total, and thus does not count towards flair.

Honestly, I feel like maybe you could split off the giveaway/contests section for /r/pokemontrades into its own thing.

**Comment by YaManicKill** [comment]
You sure? I tested this one. I would really father not have a separate
section.

**Comment by NotRaia** [comment]
I'll try again later to confirm.
