### ISSUE TITLE
I can apply for involvement flair on FlairHQ, but not on FAPP

### ISSUE THREAD

**Issue by NotRaia** [YaManicKill/flairhq#224]
On FAPP, it is forever greyed out. On FlairHQ, if I meet the number requirements, it works.

**Comment by YaManicKill** [comment]
>_>

It's not an svex flair. Why did you put the sub as svex?

-------------------------------------

Alistair McKinlay
alistair@10people.co.uk
http://www.10people.co.uk

**Comment by NotRaia** [comment]
I had to set it that way to be able to put everything to 0, because I think filling a number in for contests/giveaways also fills in the checks/given column.

**Comment by YaManicKill** [comment]
Yeah, but conversely, it sets both to 0 when you set 1.
