### ISSUE TITLE
Sorting the trade types

### ISSUE THREAD

**Issue by TheSonAlsoRises** [YaManicKill/flairhq#225]
I do not know if that it possible, but could the dropdown list feature subcategories, so it looks neater?

An example:

* /r/pokemontrades
     * Shiny
     * Casual
     * blah blah
* /r/SVExchange
     * Egg hatch
     * etc.
* Misc/other subs
     * Misc

**Comment by YaManicKill** [comment]
Something like this? http://codepen.io/YaManicKill/pen/wBEZRQ

I can do that. I don't think I can do it indented, but I can get that done.
That's a nice idea, makes it much clearer what they are for.

**Comment by YaManicKill** [comment]
Actually, tell a lie...I can indent. Just updated with that.

**Comment by TheSonAlsoRises** [comment]
Exactly what I was looking for. Thanks!

**Comment by YaManicKill** [comment]
Cool, will get that done tonight.

**Comment by NotRaia** [comment]
Erm... http://i.imgur.com/yQr14Re.png

**Comment by YaManicKill** [comment]
Woops
