### ISSUE TITLE
Entries being incorrectly deleted

### ISSUE THREAD

**Issue by TheSonAlsoRises** [YaManicKill/flairhq#228]
Basically this:

https://www.reddit.com/r/pokemontrades/comments/2z180p/changes_to_our_flair_system/cpfxdla?context=3

**Comment by YaManicKill** [comment]
Yeah, I think this was because I forgot to update the version number so
browsers cache the javascript. This can cause issues :-\ I've let them know
and asked them to check if it's fixed.

-------------------------------------

Alistair McKinlay
alistair@10people.co.uk
http://www.10people.co.uk

**Comment by YaManicKill** [comment]
I can't be bothered finding the modmail for this, but I'm pretty sure I fixed it. I remember doing that.
