### ISSUE TITLE
User not displayed in free tradebacks/redeem list

### ISSUE THREAD

**Issue by NotRaia** [YaManicKill/flairhq#230]
When entering a free tradeback/redemption, it asks you to fill in the user, but the user doesn't get displayed on the reference.

**Comment by YaManicKill** [comment]
Check this one as well?

**Comment by not-an-aardvark** [comment]
The user is not displayed [here](https://i.gyazo.com/6485f60f17221c2123863b6556e05495.png), but it is displayed [here](https://i.gyazo.com/f17fc12b71bc865cdaddd238d92606af.png).

**Comment by YaManicKill** [comment]
Oh yeah, that display is totally messed up. Leaving this one open then. Will get to it.
