### ISSUE TITLE
Possible issue validating trade count for applications

### ISSUE THREAD

**Issue by NotRaia** [YaManicKill/flairhq#251]
https://www.reddit.com/message/messages/3s39kt

I'm not sure what happened, because on both my mod account and my alt, I am unable to apply for anything I don't have sufficient trades for. Maybe he had two more trades and then deleted them?

**Comment by YaManicKill** [comment]
Yeah, I can't reproduce it either.

Are we 100% suer that he did apply for flair? That will tell me whether it's an issue with the Pending Application feature or not.

If he did actually apply for flair, I'm going to stick this on blocked and ignore it until someone else has the same issue. I assume he's just done something weird somewhere.

**Comment by NotRaia** [comment]
Yes, I denied his application. Maybe we should ask him if he had 10 trades logged at the time that he applied.
