### ISSUE TITLE
Preview for flair setting is broken

### ISSUE THREAD

**Issue by Cu3PO42** [YaManicKill/flairhq#267]
Steps to reproduce:

1. Enter Friend Code.

Entering additional data did not change anything for me.

<img width="904" alt="screen shot 2015-09-03 at 21 45 10" src="https://cloud.githubusercontent.com/assets/5256300/9669018/19f99188-5285-11e5-9561-b062361fd994.png">

EDIT: Console output:

    Error: undefined is not an object (evaluating 'games[j].tsv')
    createdFlairText

    c
    $digest
    $apply

    c
    (anonymous function)
    (anonymous function)
    $digest
    $apply
    (anonymous function)
    c

**Comment by YaManicKill** [comment]
Oh yeah, this was fixed yesterday.
