### ISSUE TITLE
Autofill for existing flair broken

### ISSUE THREAD

**Issue by Cu3PO42** [YaManicKill/flairhq#269]
<img width="906" alt="screen shot 2015-09-05 at 09 27 38" src="https://cloud.githubusercontent.com/assets/5256300/9698312/a38b172e-53b0-11e5-9573-3b7332bcfb18.png">

To me this looks like FHQ is trying to autofill the information from my current flair, which is not quite working yet, apparently.

For reference:  
Ptrades flair: `4098-3192-6085 || Cu3PO42 (X)`
SVeX flair: `4098-3192-6085 || Cu3PO42 (X), Cu3PO42 (ΩR) || 3103`

**Comment by YaManicKill** [comment]
Fixed. I had forgotten about having multiple IGNs.
