### ISSUE TITLE
Can't unselect a game version

### ISSUE THREAD

**Issue by TheSonAlsoRises** [YaManicKill/flairhq#272]
There should be an option to pick "None" or something, if you first select a game version but choose not to display it in the end (not enough space, redundant info, etc.).

**Comment by YaManicKill** [comment]
Hmmm, do we not require people to have a game version currently? Do we want to remove that requirement?

**Comment by TheSonAlsoRises** [comment]
It was never mandatory, and it can be useful in case you want to save space in your flair.

**Comment by TheSonAlsoRises** [comment]
And the issue is marked as closed, but there is still no way to unselect a game version after you have picked one.
