### ISSUE TITLE
"Set Flair Text" only preloads first TSV by default

### ISSUE THREAD

**Issue by not-an-aardvark** [YaManicKill/flairhq#282]
See https://imgur.com/a/8AaB9. Note that the second TSV is 4015, but it defaults to XXXX in the "Set Flair Text" screen.

**Comment by YaManicKill** [comment]
Ah yes, I forgot to fix this as well.

**Comment by YaManicKill** [comment]
Fixed. Not deployed yet, will do it before I go to bed.
