### ISSUE TITLE
"Too long" flairs getting blocked

### ISSUE THREAD

**Issue by DoubleFried** [YaManicKill/flairhq#284]

**Comment by DoubleFried** [comment]
A flair without TSV can get blocked, as the XXXX on SV Exchange puts it over the limit, while the || XXXX is pretty superflous especially as people that don't know their TSV probably don't care about SV Ex

**Comment by YaManicKill** [comment]
Not sure. I'll have to think about this.

**Comment by YaManicKill** [comment]
Not had any complaints from anyone, so I'm going to close this just now.
