### ISSUE TITLE
Invalid FCs are seemingly accepted.

### ISSUE THREAD

**Issue by DoubleFried** [YaManicKill/flairhq#287]
e.g. '3'

**Comment by DoubleFried** [comment]
If they aren't accepted, there's no proper error message

**Comment by YaManicKill** [comment]
Can you clear your cache and see if it's fixed?

**Comment by YaManicKill** [comment]
I'm going to close this tomorrow unless you let me know it is still an issue for you. I can't recreate this at all.

**Comment by YaManicKill** [comment]
Alrighty, as mentioned I had a fix but hadn't pushed it up. It is now deployed.
