### ISSUE TITLE
IGNs don't get automatically loaded into Set Flair Text while TSVs/FCs do

### ISSUE THREAD

**Issue by DoubleFried** [YaManicKill/flairhq#288]

**Comment by YaManicKill** [comment]
This is because you have no game set, and I currently rely on that. I'll have to figure this one out. It's a bit tricky.

**Comment by YaManicKill** [comment]
Should be fixed on almost everything. 

Only current issue (because damn, it's a difficult one and I can't be bothered with it) is if you have multiple IGNs, none with games, you will only get 1 IGN auto filled in.
