### ISSUE TITLE
FlairHQ app has default 'question mark' image on reddit

### ISSUE THREAD

**Issue by not-an-aardvark** [YaManicKill/flairhq#319]
[Current question mark icon](https://gyazo.com/27e5a221a3f8df65e8d58e261b8d65b1)

[Potential improved icon](https://gyazo.com/a9f36a39d6d1912cf1573b3a34888308)

(The logo from the second link is just [this](https://github.com/YaManicKill/flairhq/blob/master/assets/images/fhq-500.png) image.)

**Comment by YaManicKill** [comment]
Done
