### ISSUE TITLE
/clearsession doesn't work

### ISSUE THREAD

**Issue by not-an-aardvark** [YaManicKill/flairhq#354]
`/clearsession/<username>` gives the 'success' message, but the user's sessions are not actually cleared. Presumably it's searching for the user's sessions in the wrong place for some reason, and upon finding no sessions to remove, it's claiming that the task was successful.

(This is a bit strange, because it works fine on the dev version. Perhaps the session variables are stored differently on production.)

**Comment by YaManicKill** [comment]
We fixed this by moving the beta server to use Session in the database rather than Session-prod. We'll switch the prod server over when we launch this version.
