### ISSUE TITLE
Users can avoid entering an IGN in the Set Flair Text dialog

### ISSUE THREAD

**Issue by SnowPhoenix** [YaManicKill/flairhq#369]
For some reason, FlairHQ allows a user to set their flair text even if all entries for games are removed using the trash can icon.

**Comment by YaManicKill** [comment]
Just to throw the discussion we had in the irc before I forget about it:

11:09 YaManicKill I guess there are 2 parts to that:
11:09 YaManicKill 1. Don't let them have an empty list of games
11:10 YaManicKill 2. Fix the freakin' regex 
11:10 SnowPhoenix  Oh. If we're just going for a "please don't change the string" error with those, I could probably give you an alternative regex.
11:11 But yeah, point 1 is probably something you could better handle.
11:23 YaManicKill Point one is pretty easy to fix.
11:23 YaManicKill TBH, I want to change how I check regex.
11:23 YaManicKill So, currently I check the whole string as a onner.
11:23 SnowPhoenix  I was actually just looking at the regex. It really should be blocking that.
11:23 YaManicKill What I want to do is split it into it's smaller parts (split on "||") and check those. It'll make it much easier to do, tbh.
11:23 SnowPhoenix  Ah, yeah.
11:24 YaManicKill Especially as I have a "." in that regex somewhere :-P
11:24 YaManicKill That will cause problems.
11:24 SnowPhoenix  I don't see a .
11:25 SnowPhoenix  But yeah, would probably be good to validate everything individually like you said.
11:25 YaManicKill Ah no, it's [^|-] or something
11:26 SnowPhoenix  Ah.
11:26 YaManicKill Anyway, yeah, that's on my to-do list. Split it into sections from ||, then split those sections from "," and check each thing individually :-P
11:26 SnowPhoenix  Alright, makes sense.
