### ISSUE TITLE
Improve watch for grunt

### ISSUE THREAD

**Issue by YaManicKill** [YaManicKill/flairhq#427]
Some things are unnecessary to do on all watches (for example, we don't need to do less when we change a JS) and the browserify seems...kinda slow.

Also, I want to add this to my local.js (and the example, with a comment for dev)

  log: {
    level: "verbose"
  }

**Comment by not-an-aardvark** [comment]
Not sure if this is what you meant, but we should also change all our `console.log` statements to `sails.log`, `sails.verbose`, `sails.warn`, `sails.debug`, etc. so that they'll be better prioritized.

**Comment by YaManicKill** [comment]
Well yes, we should do that as well, but that's unrelated to this. I thought I had added a ticket for that.

**Comment by YaManicKill** [comment]
Created #428
