### ISSUE TITLE
Have the system automatically submit a flair app when user reaches eligibility?

### ISSUE THREAD

**Issue by SnowPhoenix** [YaManicKill/flairhq#445]
This was discussed briefly, and as requested I'm leaving a summary here for further thought/discussion and possible implementation.

The question is whether it would it be worthwhile to have the system automatically submit a flair application on behalf of a user when they have entered the required amount of trades. Here are some thoughts on it so far:

Pro:

* **More convenient and intuitive for the user**, as it doesn't involve the second step of clicking "Apply for Flair" after inputting their trades.

Con:

* **Redundant flair applications if user intends to skip a flair level:** Not necessarily that big of a deal, though, as we could deny all the apps except the highest one they actually qualify for after entries are reviewed, and it gives up the option of granting them the next flair down if one or two invalid entries make them ineligible for the level they actually applied for. Alternatively, it would probably be feasible to make the system dismiss any pending apps when submitting a higher-level one.

Both:

* **Users would be unable to maintain a lower level flair when adding trades:** This would add additional complaints about "But I liked the other flair more!" and may ultimately be the dealbreaker, but as stated in the /r/pokemontrades flair guide: "Trade flair does not exist for aesthetic purposes: it was set up to provide a way for users to help judge trustworthiness when trading with people."

**Comment by YaManicKill** [comment]
This wasn't the one I wanted you to submit. It was the icon for notes. But we should probably have a discussion about this, too.

**Comment by SnowPhoenix** [comment]
Heh. Yeah, realized that was probably the case as soon as I finished writing this up. The other one momentarily slipped my mind as we had quickly moved onto this topic, but it's submitted now as #446. After looking at #242, I think that will alleviate any issues that would make this one useful anyway, so while I'm open to further discussion, I'm also open to closing this one whenever.

**Comment by YaManicKill** [comment]
Yeah. #226 was my thinking as well for this.

**Comment by YaManicKill** [comment]
Sorry, #242
