### ISSUE TITLE
Fitting into window

### ISSUE THREAD

**Issue by Ceraphyne** [YaManicKill/flairhq#96]
A small range of window size seems to be somewhat trippy and doesn't quite fit, requiring side scrolling to view the whole window

Specifically seen in the second image, goes back to normal in image 1 & 3

![screenshot 2014-10-20 05 59 08](https://cloud.githubusercontent.com/assets/9310345/4694907/e18d24a8-57db-11e4-9f4e-28aabcba5553.png)
![screenshot 2014-10-20 05 59 57](https://cloud.githubusercontent.com/assets/9310345/4694908/e1921382-57db-11e4-94a2-2f936e8acedf.png)
![screenshot 2014-10-20 06 02 13](https://cloud.githubusercontent.com/assets/9310345/4694909/e19677ec-57db-11e4-8729-bd7bcf1f8423.png)

**Comment by YaManicKill** [comment]
Alrighty, as far as I can see, it doesn't have any issues anymore. I'm closing this one. Open a new one if you see anymore issues.
